apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: approve-use-api-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "delete", "watch", "list", "proxy", "deletecollection", "patch"]
