apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: token-group-role-binding
subjects:
- kind: Group
  name: system:bootstrappers
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: ClusterRole
 name: approve-use-api-role
 apiGroup: rbac.authorization.k8s.io
