apiVersion: v1
kind: PersistentVolume
metadata:
  name: eyesone-nfs-server-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/ms-rank
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eyesone-nfs-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode:
  resources:
    requests:
      storage: 20Gi
