kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: nginx-ingress-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "configmaps", "pods", "secrets"]
  verbs: ["get"]
  #
  apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints"]
  verbs: ["get"]
