apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: nginx-ingress-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: nginx-ingress-serviceaccount
roleRef:
 kind: ClusterRole
 name: nginx-ingress-clusterrole
 apiGroup: rbac.authorization.k8s.io
