kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: nginx-ingress-clusterrole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "ingresses"]
  verbs: ["get", "watch", "list"]
  #
  apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "endpoints", "nodes", "pods", "secrets"]
  verbs: ["watch", "list"]
  #
  apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get"]
  #
  apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["create", "patch"]
  #
  apiGroups: [""] # "" indicates the core API group
  resources: ["ingresses/status"]
  verbs: ["update"]
